Fix positioning on multiple screens
JezerM/web-greeter pull request #35
Opened 2022-03-25 08:23 UTC by guillaumeboehm

The change to browser.py should fix issues on multiple screens such as in issue #29.

I also added a cursor resize to the Xgreeter which seems reasonable to me, but I guess you can remove it if you think it shouldn't be here.

2022-03-25 17:39 UTC, JezerM requested changes
Looks nice! I didn't know about `QGuiApplication` existence and that it's a superclass of QApplication. So, `Application.desktop` property could be removed to use `QGuiApplication` methods instead. Also, this could even make possible a multi-monitor support in a future~

2022-03-25 17:39 UTC, JezerM commented on dist/Xgreeter
> +export XCURSOR_SIZE=16
```suggestion
```

Yeah, I don't think this should be here as this would enforce every system to have this cursor size (on web-greeter).

2022-03-26 13:32 UTC, guillaumeboehm commented
I'm not sure what you mean by multiple monitor support If it's not what I added in browser.py? So I searched for the use of Application.desktop in the code and couldn't find any, I would be happy to work on this a little bit if it's in my capabilities. Could you detail quickly what you mean ?

2022-03-26 16:20 UTC, JezerM commented
What this PR does is to set the primary window in the primary screen/display, which should fix the #29 issue by setting web-greeter's window in the main monitor. However, this is not a multi-monitor support, as the rest of monitors would still be blank without any window.

By **Multi-Monitor** support I mean something like JezerM/nody-greeter#11 does, which creates multiple IPC-interconnected windows for each monitor, and allows to set a primary and secondary HTML files whether the monitor is primary or not with a `index.yml` configuration inside the theme directory.

The `Application.desktop` property, a QDesktopWidget, was previously used to get the screen properties (like geometry), which is now unused with this PR. Also, the PyQt5 documentation declares most of its methods as deprecated, so I was just saying that this property could be removed~

https://github.com/JezerM/web-greeter/blob/26de61ecb36c7bb2259161d0b1a37b107c665bdb/src/browser/browser.py#L118

2022-03-26 16:21 UTC, JezerM approved these changes
However, if this PR is just meant to fix the positioning on multiple screens, this should be done~

2022-03-26 18:43 UTC, guillaumeboehm commented
I see! Well that's interesting, I think I'll try to look into multi-monitor support then. Not sure I'll get somewhere but I'll create a PR if I manage something!

2022-03-26 19:09 UTC, JezerM commented
Nice~ Then, this PR will be merged. Thanks!

2022-03-26 19:09 UTC, merged